FROM node:alpine as ui-builder
WORKDIR '/app'
COPY ./package.json .
RUN npm install
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN git clone https://github.com/fancyapps/fancybox.git /app/node_modules/@fancyapps/fancybox
COPY server/client .
RUN npm run build

FROM python:3.7
WORKDIR '/app'
COPY server .
COPY --from=ui-builder /app/dist /app/client/dist
RUN pip install -r requirements.txt
RUN mkdir /app/vcelnice/logs
RUN python manage.py migrate
RUN python manage.py collectstatic

EXPOSE 8080
ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]